spring:
  application:
    name: ali.su.cft2j02.task05
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/cft2j02
    username: pguser
    password: pass
    driver-class-name: org.postgresql.Driver
rest:
  product-endpoint: "/corporate-settlement-instance"
  account-endpoint: "/corporate-settlement-account"